/**
 * WORK — the finished-ish things.
 */
export const projects = [
  {
    slug: 'yam',
    title: 'YAM',
    fullTitle: 'Your AI Meal',
    year: '2024',
    type: 'university capstone / AI',
    status: 'WORKS',
    featured: true,
    color: 'lime',
    visual: 'meal',
    note: 'group project — we survived',
    description:
      'An AI recipe generator and meal recommender. Tell it what’s in your pantry and it suggests what to cook — with calories, water intake and other basics tuned to you.',
    role: 'capstone team member',
    technologies: [],
    images: [],
    videos: [],
    links: [],
    github: '',
    body: [
      { type: 'p', text: 'YAM (Your AI Meal) was our university capstone: a group project that tried to answer a very ordinary question — “what should I eat tonight, with what I already have?”' },
      { type: 'h', text: 'what it does' },
      { type: 'list', items: [
        'generates recipes from the ingredients you pick, or what’s in your pantry',
        'recommends meals based on your preferences',
        'tracks the basics — calories, water intake and more — based on your details',
      ] },
      { type: 'p', text: 'The interesting part was never the model on its own. It was deciding what to ask people, and what not to. Nobody wants to fill in a nutrition survey when they’re hungry.' },
    ],
  },
  {
    slug: 'pupsplash',
    title: 'Pupsplash',
    year: '2025',
    type: 'hobby project / client management',
    status: 'WORKS',
    home: true,
    color: 'pink',
    visual: 'pupsplash',
    note: 'built for the dogs, mostly',
    description:
      'A client management system for dog groomers — clients, pets, appointments and grooming history, in one calm place.',
    role: 'solo — design and build',
    technologies: ['React'],
    images: [],
    videos: [],
    links: [],
    github: '',
    body: [
      { type: 'p', text: 'Groomers juggle a lot: owners, appointments, and dogs with strong opinions about the dryer. Pupsplash keeps all of it in one place.' },
      { type: 'p', text: 'It’s a hobby project, which means it gets rebuilt every time I learn a better way to do something in React.' },
      { type: 'h', text: 'what’s inside' },
      { type: 'list', items: ['client and pet profiles', 'appointment booking', 'grooming history and notes', 'a very quiet interface'] },
    ],
  },
  {
    slug: 'smarthire',
    title: 'SmartHire',
    year: '2025',
    type: 'AI / recruiting tool',
    status: 'WORKS',
    home: true,
    color: 'lavender',
    visual: 'smarthire',
    note: 'reads resumes so you don’t have to',
    description:
      'Candidates upload their resumes; recruiters get the strongest matches for a role at the top — instead of a pile of PDFs.',
    role: 'design and build',
    technologies: [],
    images: [],
    videos: [],
    links: [],
    github: '',
    body: [
      { type: 'p', text: 'Hiring usually starts with a pile: dozens of resumes for one role, and not enough time to read them properly. SmartHire sorts the pile.' },
      { type: 'h', text: 'two sides' },
      { type: 'list', items: [
        'candidates — upload a resume and apply',
        'recruiters — upload or collect resumes for a role',
        'the top candidates are filtered and ranked against what the role needs',
      ] },
      { type: 'p', text: 'The hard part isn’t reading a resume. It’s deciding what “a good match” means, and being able to explain why someone ranked where they did.' },
    ],
  },
  {
    slug: 'recall',
    title: 'Recall',
    year: '2026',
    type: 'AI / retrieval',
    status: 'TESTING',
    sample: true,
    color: 'orange',
    visual: 'recall',
    note: 'it found notes I forgot I wrote',
    description:
      'Ask questions to everything you’ve ever written down. Retrieval over personal notes, with sources — and honest “I don’t know”s.',
    role: 'solo',
    technologies: ['Python', 'embeddings', 'vector search'],
    images: [],
    videos: [],
    links: [],
    github: '',
    body: [
      { type: 'p', text: 'Sample project — replace with a real one.' },
    ],
  },
  {
    slug: 'pricy',
    title: 'Pricy',
    year: '2017 → 2018',
    type: 'first capstone / chatbot',
    status: 'ARCHIVED',
    archived: true,
    color: 'blue',
    visual: 'pricy',
    description:
      'A chatbot that compared prices. My first capstone — and the first time I asked “but how does it actually understand me?”',
    role: 'student, very tired',
    technologies: ['Python', 'NLTK', 'a lot of regex'],
    images: [],
    videos: [],
    links: [],
    github: '',
    body: [
      { type: 'p', text: 'In 2017 chatbots were mostly decision trees wearing a trench coat. I wanted mine to be smarter than that, so I started reading about neural networks. At night. For months. Stack Overflow answers, old chatbot research papers, anything that explained how any of it actually worked.' },
      { type: 'p', text: 'Pricy could take a question like “cheapest headphones under $100” and go looking. It understood maybe fourteen ways of asking that. Everything else got “sorry, I didn’t get that.”' },
      { type: 'quote', text: 'I didn’t understand how it worked. I just knew I wanted to.' },
      { type: 'p', text: 'It isn’t a good chatbot by today’s standards. It’s where the curiosity started.' },
    ],
  },
  {
    slug: 'next',
    title: 'Next',
    year: '2026 →',
    type: 'probably AI',
    status: "I DON'T KNOW YET",
    future: true,
    color: 'orange',
    visual: 'next',
    description: 'Not started. Or maybe started three times. This space is reserved.',
    role: '?',
    technologies: [],
    images: [],
    videos: [],
    links: [],
    github: '',
    body: [],
  },
]

export const getProject = (slug) => projects.find((p) => p.slug === slug)
